Update use of js-yaml for compatibility with newer type defintions
A [recent change][0] changed the return type of `safeLoad` from `any` to
`object`. Accessing any property on a value of type `object` generates a
compiler error.

```
src/config.ts(168,17): error TS2339: Property 'apiVersion' does not exist on type 'object'.
```

[0]: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/ae9aff4a0c0ccdc224583f0f7f84d3a5b7bc3483